import requests
import urllib3
from typing import Dict, Any

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


class WAFDetector:
    def __init__(self, url: str, timeout: float = 10.0):
        self.url = url if url.startswith('http') else f'https://{url}'
        self.timeout = timeout
        self.payload_timeout = 6.0

        self.WAF_SIGNATURES = {
            'Cloudflare': {
                'headers': ['cf-ray', 'cf-cache-status', 'cf-request-id'],
                'body':    ['cloudflare', 'attention required! | cloudflare', 'ray id:'],
                'cookies': ['__cfduid', 'cf_clearance']
            },
            'AWS WAF': {
                'headers': ['x-amzn-requestid', 'x-amz-cf-id'],
                'body':    ['aws waf', 'request blocked by aws'],
                'cookies': ['aws-waf-token']
            },
            'Sucuri': {
                'headers': ['x-sucuri-id', 'x-sucuri-cache'],
                'body':    ['sucuri website firewall', 'access denied - sucuri'],
                'cookies': []
            },
            'ModSecurity': {
                'headers': ['mod_security', 'modsecurity'],
                'body':    ['mod_security', 'this error was generated by mod_security'],
                'cookies': []
            },
            'Imperva / Incapsula': {
                'headers': ['x-iinfo', 'x-cdn'],
                'body':    ['incapsula incident id', 'powered by incapsula'],
                'cookies': ['visid_incap', 'incap_ses']
            },
            'Akamai': {
                'headers': ['x-check-cacheable', 'akamai-cache-status', 'x-akamai-transformed'],
                'body':    ['akamai reference', 'access denied - akamai'],
                'cookies': ['ak_bmsc', 'bm_sv']
            },
            'Wordfence': {
                'headers': [],
                'body':    ['generated by wordfence', 'your access to this site has been limited by wordfence'],
                'cookies': ['wfvt_']
            },
            'Nginx WAF': {
                'headers': ['x-nginx-cache'],
                'body':    ['openresty', 'naxsi'],
                'cookies': []
            }
        }

    def _check_signatures(self, resp, sigs: dict) -> tuple[int, list]:
        score = 0
        evidence = set()

        resp_headers = {k.lower(): v.lower() for k, v in resp.headers.items()}
        resp_body    = resp.text.lower()
        resp_cookies = {k.lower() for k in resp.cookies.keys()}

        for header in sigs['headers']:
            if header.lower() in resp_headers:
                score += 2
                evidence.add(f"Header: {header}")

        for keyword in sigs['body']:
            if keyword.lower() in resp_body:
                score += 1
                evidence.add(f"Body: {keyword}")

        for cookie in sigs['cookies']:
            if any(cookie.lower() in c for c in resp_cookies):
                score += 2
                evidence.add(f"Cookie: {cookie}")

        return score, evidence

    def run(self) -> Dict[str, Any]:
        results = {
            'waf_detected': False,
            'waf_name':     None,
            'evidence':     [],
            'error':        None
        }

        try:
            normal_resp = requests.get(
                self.url,
                timeout=self.timeout,
                verify=False,
                headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
            )

            try:
                payload_resp = requests.get(
                    f"{self.url}/?q=<script>alert(1)</script>&id=1' OR '1'='1",
                    timeout=self.payload_timeout,
                    verify=False,
                    headers={'User-Agent': 'sqlmap/1.0'}
                )
            except requests.exceptions.Timeout:
                payload_resp = None

            detected_wafs = []

            for waf_name, sigs in self.WAF_SIGNATURES.items():
                total_score    = 0
                total_evidence = set()

                # Cek normal response
                score_n, evidence_n = self._check_signatures(normal_resp, sigs)

                # Cek payload response (hanya kalau tidak timeout)
                score_p, evidence_p = set(), set()
                if payload_resp is not None:
                    score_p, evidence_p = self._check_signatures(payload_resp, sigs)

                # Ambil score tertinggi (bukan dijumlah) untuk hindari double count
                total_score    = max(score_n, score_p) if payload_resp else score_n
                total_evidence = evidence_n | evidence_p

                # Minimum threshold score > 1 untuk kurangi false positive
                if total_score > 1:
                    detected_wafs.append({
                        'name':     waf_name,
                        'score':    total_score,
                        'evidence': list(total_evidence)
                    })

            if detected_wafs:
                detected_wafs.sort(key=lambda x: x['score'], reverse=True)
                top = detected_wafs[0]
                results['waf_detected'] = True
                results['waf_name']     = top['name']
                results['evidence']     = top['evidence']

            elif payload_resp is not None and payload_resp.status_code in [403, 406, 429, 503]:
                # Pastikan normal response tidak sama status-nya (hindari false positive)
                if normal_resp.status_code not in [403, 406, 429, 503]:
                    results['waf_detected'] = True
                    results['waf_name']     = 'Unknown WAF'
                    results['evidence']     = [f"Blocked with HTTP {payload_resp.status_code} on malicious payload"]

        except requests.exceptions.ConnectionError:
            results['error'] = 'Connection failed — target unreachable'
        except requests.exceptions.Timeout:
            results['error'] = 'Request timed out'
        except Exception as e:
            results['error'] = str(e)

        return results