version: '3.8'

services:
  backend:
    build: .
    container_name: deepscan_backend
    restart: always
    network_mode: "host" # Supaya bisa connect ke database MySQL di localhost VPS
    env_file:
      - .env
    volumes:
      - ./data:/app/data
