# helpers/waf_checker.py — Universal WAF Detection & Bypass Helper
"""
Modul universal untuk mendeteksi keberadaan Web Application Firewall (WAF)
dan menyediakan strategi bypass yang bisa dipakai semua scanner module.

Penggunaan:
    from helpers.waf_checker import WAFChecker

    waf = WAFChecker(base_url, http_client)
    is_waf = waf.detect()              # True/False
    info    = waf.get_info()           # dict detail WAF
    headers = waf.get_bypass_headers() # list[dict] bypass headers
"""
from typing import Dict, List, Optional, Any


# ── WAF Signature Database ────────────────────────────────────────────────────

# Header-based signatures  (header_name_lowercase -> WAF name)
WAF_HEADER_SIGNATURES: Dict[str, str] = {
    'cf-ray':               'Cloudflare',
    'cf-mitigated':         'Cloudflare',
    'cf-chl-bypass':        'Cloudflare',
    'x-sucuri-id':          'Sucuri',
    'x-sucuri-cache':       'Sucuri',
    'x-firewall':           'Generic Firewall',
    'x-waf':                'Generic WAF',
    'x-cdn':                'CDN/WAF',
    'x-akamai-transformed': 'Akamai',
    'x-amz-cf-id':          'AWS CloudFront',
}

# Body-based signatures  (substring di body lowercase -> WAF name)
WAF_BODY_SIGNATURES: List[Dict[str, str]] = [
    # Cloudflare — HANYA signature dari challenge/block page, bukan CDN biasa
    # 'cloudflare' alone terlalu broad (match di RocketLoader, analytics, footer)
    {'sig': 'attention required! | cloudflare', 'waf': 'Cloudflare'},
    {'sig': 'just a moment',                    'waf': 'Cloudflare'},
    {'sig': 'checking your browser',            'waf': 'Cloudflare'},
    {'sig': 'enable javascript and cookies',    'waf': 'Cloudflare'},
    {'sig': 'ddos protection by cloudflare',    'waf': 'Cloudflare'},
    {'sig': 'ray id:',                          'waf': 'Cloudflare'},
    {'sig': 'cf-browser-verification',          'waf': 'Cloudflare'},
    {'sig': 'managed challenge',                'waf': 'Cloudflare'},
    # Sucuri
    {'sig': 'sucuri website firewall', 'waf': 'Sucuri'},
    {'sig': 'access denied - sucuri',  'waf': 'Sucuri'},
    # AWS WAF
    {'sig': 'aws waf',                 'waf': 'AWS WAF'},
    {'sig': 'request blocked by aws',  'waf': 'AWS WAF'},
    # Imperva / Incapsula
    {'sig': 'incapsula incident',      'waf': 'Imperva Incapsula'},
    {'sig': 'powered by incapsula',    'waf': 'Imperva Incapsula'},
    # Akamai
    {'sig': 'akamai ghost',            'waf': 'Akamai'},
    {'sig': 'ak_bmsc',                 'waf': 'Akamai'},
    # DDoS-Guard
    {'sig': 'ddos-guard',              'waf': 'DDoS-Guard'},
    # Wordfence
    {'sig': 'wordfence',               'waf': 'Wordfence'},
    {'sig': 'generated by wordfence',  'waf': 'Wordfence'},
    # ModSecurity
    {'sig': 'mod_security',            'waf': 'ModSecurity'},
    {'sig': 'modsecurity',             'waf': 'ModSecurity'},
    # Generic (hanya yang sangat spesifik)
    {'sig': 'this page is protected',  'waf': 'Generic WAF'},
    {'sig': 'sorry, you have been blocked', 'waf': 'Generic WAF'},
    {'sig': 'web application firewall', 'waf': 'Generic WAF'},
    {'sig': 'your request has been blocked', 'waf': 'Generic WAF'},
]

# Cookie-based signatures  (cookie name lowercase -> WAF name)
WAF_COOKIE_SIGNATURES: Dict[str, str] = {
    'cf_clearance':   'Cloudflare',
    '__cfduid':       'Cloudflare',
    'aws-waf-token':  'AWS WAF',
    'incap_ses_':     'Imperva Incapsula',
    'visid_incap_':   'Imperva Incapsula',
    'ak_bmsc':        'Akamai',
    '_bm_sv':         'Akamai',
    'sucuri_cloudproxy': 'Sucuri',
}


# ── WAF Bypass Headers ───────────────────────────────────────────────────────
# Beberapa WAF trust header dari reverse proxy, ini bisa bypass IP-based rules

WAF_BYPASS_HEADERS: List[Dict[str, str]] = [
    {},  # no extra headers (baseline)
    {'X-Forwarded-For': '127.0.0.1'},
    {'X-Real-IP': '127.0.0.1'},
    {'X-Originating-IP': '127.0.0.1'},
    {'CF-Connecting-IP': '127.0.0.1'},
    {'True-Client-IP': '127.0.0.1'},
    {'X-Client-IP': '127.0.0.1'},
    {'X-Forwarded-For': '127.0.0.1', 'X-Real-IP': '127.0.0.1'},
    {'X-Forwarded-Host': 'localhost'},
    {'X-Custom-IP-Authorization': '127.0.0.1'},
    {'Forwarded': 'for=127.0.0.1;by=127.0.0.1;host=localhost'},
]


# ── WAF Test Payloads ─────────────────────────────────────────────────────────
# Payload yang sengaja memancing WAF — hanya 2 untuk menghindari rate-limiting
# (aslinya tiap modul hanya kirim 1 probe: <script>alert(1)</script>)

WAF_PROBE_PAYLOADS: List[str] = [
    '<script>alert(1)</script>',
    "' OR '1'='1",
]


# ── Main WAF Checker Class ────────────────────────────────────────────────────

class WAFChecker:
    """
    Universal WAF detector yang bisa dipakai oleh semua vulnerability scanner.

    Contoh penggunaan di checker module:
        waf = WAFChecker(self.base_url, self._client)
        self._waf_detected = waf.detect()
        self._waf_info     = waf.get_info()
    """

    def __init__(self, base_url: str, http_client, headers: Optional[Dict] = None):
        """
        Args:
            base_url:    URL target (e.g. 'https://example.com')
            http_client: Instance HttpClient dari helpers.http_client
            headers:     Default headers untuk request (opsional)
        """
        self.base_url    = base_url.rstrip('/')
        self._client     = http_client
        self._headers    = headers or {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                          'AppleWebKit/537.36 (KHTML, like Gecko) '
                          'Chrome/131.0.0.0 Safari/537.36',
            'Accept': 'text/html,application/xhtml+xml,*/*',
        }
        self._detected        = False
        self._waf_name        = 'Unknown'
        self._detection_method = ''
        self._blocked_status   = 0
        self._checked          = False

    # ── Core detection ────────────────────────────────────────────────────────

    def detect(self) -> bool:
        """
        Deteksi WAF dengan mengirim probe request.
        Return True jika WAF terdeteksi.
        Hasil di-cache — multiple calls tidak kirim request ulang.
        """
        if self._checked:
            return self._detected

        self._checked = True

        # 1. Fetch normal request sebagai baseline
        r_normal = self._client.get(self.base_url, headers=self._headers)

        # 2. Kirim probe payload yang memancing WAF
        #    Hanya detect WAF jika probe response BERBEDA dari normal
        #    (WAF headers pada normal request = CDN, bukan blocking)
        for payload in WAF_PROBE_PAYLOADS:
            test_url = f"{self.base_url}/?x={payload}"
            r = self._client.get(test_url, headers=self._headers)
            if not r:
                continue

            # Cek WAF-specific headers (hanya yang menandakan BLOCKING)
            waf_headers = {'x-sucuri-id', 'x-firewall', 'x-waf',
                           'x-incap-ses', 'cf-mitigated', 'cf-chl-bypass'}
            resp_header_keys = {k.lower() for k in r.headers.keys()}
            matched_waf_headers = waf_headers & resp_header_keys
            if matched_waf_headers:
                header_name = next(iter(matched_waf_headers))
                self._detected        = True
                self._waf_name        = WAF_HEADER_SIGNATURES.get(
                    header_name, 'Unknown WAF'
                )
                self._detection_method = f'blocking header: {header_name}'
                self._blocked_status   = r.status_code
                return True

            # Cek body-based WAF signatures
            waf_name = self._check_body(r)
            if waf_name:
                self._detected        = True
                self._waf_name        = waf_name
                self._detection_method = 'body signature'
                self._blocked_status   = r.status_code
                return True

            # Cek Cloudflare challenge page (bukan sekedar cf-ray header)
            if self.is_cloudflare_page(r.text):
                # Pastikan ini memang blocking, bukan halaman biasa
                if not (r_normal and self.is_cloudflare_page(r_normal.text)):
                    self._detected        = True
                    self._waf_name        = 'Cloudflare'
                    self._detection_method = 'cloudflare challenge page'
                    self._blocked_status   = r.status_code
                    return True

            # 403 pada probe tapi normal request OK -> WAF blocking
            if r.status_code == 403:
                if r_normal and r_normal.status_code != 403:
                    self._detected        = True
                    self._waf_name        = 'Unknown WAF'
                    self._detection_method = '403 on probe payload'
                    self._blocked_status   = 403
                    return True

        return False

    def _check_headers(self, response) -> Optional[str]:
        """Cek WAF dari response headers."""
        if not response or not hasattr(response, 'headers'):
            return None

        resp_headers = {k.lower(): v for k, v in response.headers.items()}

        for header_key, waf_name in WAF_HEADER_SIGNATURES.items():
            if header_key in resp_headers:
                return waf_name
        return None

    def _check_body(self, response) -> Optional[str]:
        """Cek WAF dari response body."""
        if not response or not hasattr(response, 'text'):
            return None

        body_lower = response.text.lower()
        for entry in WAF_BODY_SIGNATURES:
            if entry['sig'] in body_lower:
                return entry['waf']
        return None

    def _check_cookies(self, response) -> Optional[str]:
        """Cek WAF dari response cookies."""
        if not response or not hasattr(response, 'headers'):
            return None

        set_cookie = response.headers.get('Set-Cookie', '').lower()
        for cookie_name, waf_name in WAF_COOKIE_SIGNATURES.items():
            if cookie_name in set_cookie:
                return waf_name
        return None

    # ── Public API ────────────────────────────────────────────────────────────

    def get_info(self) -> Dict[str, Any]:
        """Return detail informasi WAF yang terdeteksi."""
        if not self._checked:
            self.detect()

        return {
            'detected':         self._detected,
            'waf_name':         self._waf_name if self._detected else None,
            'detection_method': self._detection_method if self._detected else None,
            'blocked_status':   self._blocked_status if self._detected else None,
        }

    def is_detected(self) -> bool:
        """Shortcut — return True jika WAF terdeteksi (auto-detect jika belum)."""
        if not self._checked:
            self.detect()
        return self._detected

    def get_waf_name(self) -> Optional[str]:
        """Return nama WAF yang terdeteksi, atau None."""
        if not self._checked:
            self.detect()
        return self._waf_name if self._detected else None

    @staticmethod
    def get_bypass_headers() -> List[Dict[str, str]]:
        """Return list bypass headers yang bisa dicoba untuk melewati WAF."""
        return WAF_BYPASS_HEADERS

    @staticmethod
    def is_cloudflare_page(text: str) -> bool:
        """
        Cek apakah halaman adalah Cloudflare challenge/block page.
        TIDAK match pada halaman biasa yang sekedar proxied oleh CF.
        Bisa dipanggil tanpa instance — sebagai static utility.
        """
        if not text:
            return False
        body_lower = text.lower()
        # Hanya signature dari actual CF challenge/block page
        cf_challenge_sigs = [
            'just a moment',
            'checking your browser',
            'enable javascript and cookies',
            'ddos protection by cloudflare',
            'attention required! | cloudflare',
            'cf-browser-verification',
            'managed challenge',
        ]
        return any(sig in body_lower for sig in cf_challenge_sigs)

    @staticmethod
    def is_waf_block(response) -> bool:
        """
        Quick check: apakah response ini kemungkinan di-block oleh WAF.
        Berguna untuk membedakan 403 dari WAF vs 403 dari aplikasi.
        """
        if not response:
            return False

        # Status code yang umum dari WAF block
        if response.status_code in (403, 406, 429, 503):
            body_lower = getattr(response, 'text', '').lower()
            for entry in WAF_BODY_SIGNATURES:
                if entry['sig'] in body_lower:
                    return True

            # Cek header
            resp_headers = {k.lower() for k in response.headers.keys()}
            waf_headers  = {'cf-ray', 'x-sucuri-id', 'x-firewall',
                            'x-waf', 'x-incap-ses'}
            if waf_headers & resp_headers:
                return True

        return False

    def get_with_bypass(self, url: str, base_headers: Optional[Dict] = None):
        """
        Coba GET request dengan berbagai bypass headers.
        Return response pertama yang tidak di-block WAF, atau None.
        """
        headers = base_headers or self._headers
        for extra_h in WAF_BYPASS_HEADERS:
            merged = {**headers, **extra_h}
            r = self._client.get(url, headers=merged)
            if r and not self.is_waf_block(r):
                return r
        return None
